# Production Environment Override Values

## Global parameters
global:
  storageClass: "managed-premium"

## WordPress Configuration
resources:
  limits:
    cpu: 1000m
    memory: 1536Mi
  requests:
    cpu: 500m
    memory: 768Mi

## Autoscaling Parameters
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPU: 70
  targetMemory: 70
  customMetrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 1k

## Redis cache parameters
redis:
  enabled: true
  architecture: replication
  auth:
    enabled: true
    sentinel: true
  master:
    persistence:
      size: 20Gi
  replica:
    replicaCount: 2
    persistence:
      size: 20Gi

## Database Parameters
mysql:
  enabled: true
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1536Mi
    requests:
      cpu: 500m
      memory: 768Mi
  secondary:
    replicaCount: 2

## Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 2

## Backup Configuration
backup:
  enabled: true
  schedule: "0 1 * * *"
  persistence:
    enabled: true
    storageClass: "managed-premium"
    size: 100Gi
  s3:
    enabled: true
    bucket: "wordpress-backups-prod"
    region: "us-east-1"

## Monitoring and Logging
prometheus:
  metrics:
    enabled: true
  operator:
    serviceMonitor:
      enabled: true

logging:
  fluentd:
    enabled: true
  elasticsearch:
    enabled: true
  kibana:
    enabled: true

## TLS Configuration
tls:
  enabled: true
  certificateSecretName: wordpress-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer