apiVersion: pod-security.admission.config.k8s.io/v1beta1
kind: PodSecurityConfiguration
defaults:
  enforce: "restricted"
  enforce-version: "latest"
  audit: "restricted"
  audit-version: "latest"
  warn: "restricted"
  warn-version: "latest"
exemptions:
  # Exempt all Pods in the following namespaces
  namespaces:
  - kube-system
  - istio-system
  - monitoring
  - cert-manager
  - flux-system
  - argocd
  # Exempt specific Pods by name and namespace
  runtimeClasses: []
  usernames: []