apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.configmap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  my.cnf: |-
{{ .Values.configuration | indent 4 }}