apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.headless.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  {{- if .Values.headless.annotations }}
  annotations:
    {{- toYaml .Values.headless.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql