{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.rootPassword }}
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.password }}
  mysql-password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  mysql-password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.replicationPassword }}
  mysql-replication-password: {{ .Values.auth.replicationPassword | b64enc | quote }}
  {{- else }}
  mysql-replication-password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
{{- end }}