apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: lab3
spec:
  accessModes:
    - ReadWriteOnce  # Changed from ReadWriteMany for local testing
  resources:
    requests:
      storage: 2Gi
