apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: lab3
type: Opaque
data:
  # These are base64 encoded values - in production use a more secure approach
  # echo -n "rootpass" | base64
  mysql-root-password: cm9vdHBhc3M=
  # echo -n "wordpress" | base64
  mysql-user: d29yZHByZXNz
  # echo -n "pass123" | base64 
  mysql-password: cGFzczEyMw==
  # echo -n "replicator" | base64
  mysql-replica-password: cmVwbGljYXRvcg==
