apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  namespace: lab1
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:latest
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql-service.lab1.svc.cluster.local
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: wordpresspassword
    - name: WORDPRESS_DB_NAME
      value: wordpress
    ports:
    - containerPort: 80
