apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  # Use Let's Encrypt staging server for testing (doesn't count against rate limits)
  acme:
    # Let's Encrypt staging API endpoint
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address for notifications about certificate expiry
    email: your-email@example.com
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Configure challenge resolver - using HTTP-01 challenge
    solvers:
    - http01:
        ingress:
          class: nginx
