apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: lab2
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002  # Expose on a different port than lab1
  selector:
    app: wordpress
