apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: lab2
data:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_TABLE_PREFIX: wp_
  # PHP configuration - optional performance settings
  PHP_MEMORY_LIMIT: 256M
  PHP_MAX_EXECUTION_TIME: "120"
