{
 "title": "MySQL Dashboard",
 "tags": [
  "mysql",
  "database"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "MySQL Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "Connected Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_running{job=\"mysql\"}"
    }
   ]
  },
  {
   "title": "MySQL Commands Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{job=\"mysql\"}[5m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "MySQL Query Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{job=\"mysql\"}[5m])",
     "legendFormat": "Queries"
    },
    {
     "expr": "rate(mysql_global_status_questions{job=\"mysql\"}[5m])",
     "legendFormat": "Questions"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Pages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_innodb_buffer_pool_pages_data{job=\"mysql\"}",
     "legendFormat": "Data Pages"
    },
    {
     "expr": "mysql_global_status_innodb_buffer_pool_pages_free{job=\"mysql\"}",
     "legendFormat": "Free Pages"
    },
    {
     "expr": "mysql_global_status_innodb_buffer_pool_pages_dirty{job=\"mysql\"}",
     "legendFormat": "Dirty Pages"
    }
   ]
  },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received{job=\"mysql\"}[5m])",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent{job=\"mysql\"}[5m])",
     "legendFormat": "Sent Bytes"
    }
   ]
  }
 ]
}